name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Gradle Build Action
      run: gradle/gradle-build-action@v3

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: StreetMeet.apk
        path: app/build/outputs/apk/app-debug.apk
